### ISSUE TITLE
Move userId to headers

### ISSUE THREAD

**Issue by EnKarin** [EnKarin/BookCrossingServer#56]

**Comment by ishu-thakur** [comment]
Hi , i would like to pick this one , can you give me overview on this?

**Comment by EnKarin** [comment]
@ishu-thakur 
Hi!
Currently, the userId is passed as a parameter in requests. We need to move it to the request headers and fix the tests

**Comment by EnKarin** [comment]
@LukasovecSK 
Yes, sure
